from django.conf.urls import patterns, url

from main import views

urlpatterns = patterns('',
    url(r'^/?$', views.root),
    url(r'^latest/?$', views.latest),
    url(r'^user/([^/]+)/?$', views.user_page),
    url(r'^comments/([^/]+)/?$', views.post_comments_page),
    url(r'^notifications/?$', views.notifications_page),
    url(r'^api/post/hottest/?$', views.post_hottest),
    url(r'^api/post/latest/?$', views.post_latest),
    url(r'^api/post/create/?$', views.post_create),
    url(r'^api/post/delete/?$', views.post_delete),
    url(r'^api/post/([^/]+?)/upvote/?$', views.post_upvote),
    url(r'^api/post/([^/]+?)/downvote/?$', views.post_downvote),
    url(r'^api/post/([^/]+?)/unvote/?$', views.post_unvote),
    url(r'^api/post/([^/]+?)/?$', views.post_page_json),
    url(r'^api/post/by/([^/]+?)/?$', views.post_by),
    url(r'^api/comment/create/?$', views.comment_create),
    url(r'^api/comment/update/?$', views.comment_update),
    url(r'^api/comment/delete/?$', views.comment_delete),
    url(r'^api/comment/([^/]+?)/?$', views.comment_json),
    url(r'^api/comment/([^/]+?)/tree/?$', views.comment_tree),
    url(r'^api/comment/([^/]+?)/upvote/?$', views.comment_upvote),
    url(r'^api/comment/([^/]+?)/downvote/?$', views.comment_downvote),
    url(r'^api/comment/([^/]+?)/unvote/?$', views.comment_unvote),
    url(r'^api/notifications/how-many-unread/?$',
        views.activity_how_many_unread),
    url(r'^api/notifications/recent/?$', views.activity_recent),
    url(r'^api/notifications/?$', views.activity_own),
    url(r'^api/user/page-json/([^/]+)/?$', views.user_page_json),
    url(r'^api/user/set-color/?$', views.user_set_color),
)
